### ISSUE TITLE
As a Scala newbie, could you explain your usage of

### ISSUE THREAD

**Issue by sixman9** [lihaoyi/hands-on-scala-js#28]
Apologies, this is *not* an issue per se, I'm just looking for a little clarification regarding some code usage.

I'm a Java dev tinkering with Scala and while looking at your [Weather1.scala](https://github.com/lihaoyi/hands-on-scala-js/blob/master/examples/demos/src/main/scala/webpage/Weather1.scala) code I noticed the following, **class-less, 'extends'** code construct:

    object Weather1 extends{
        //Class definition code goes here....
    } //No 'with <class> usage'

After some searching I found ['Scala early definitions'](https://www.google.com/search?q=Scala+early+definitions), which makes some sense to me in respect to pre-initialising super class fields, explicitly when extra 'with <class>' definitions are made at the end of the anonymous code block. Your Weather1 code makes no further reference to extra super classes (i.e. no 'with'), so **could you explain why you make use of this extends-anonymous-class structure, thanks?**

Quoting [this](http://stackoverflow.com/questions/7579617/what-is-the-purpose-of-extending-an-anonymous-type-in-scala/12790103#12790103) stackoverflow post:

    abstract class X {
        val name: String
        val size = name.size
    }

    class Y extends {
        val name = "class Y"
    } with X

If the code were written instead as

    class Z extends X {
        val name = "class Z"
    }

then a null pointer exception would occur when Z got initialized, because size is initialized before name in the normal ordering of initialization (superclass before class).

**Comment by lihaoyi** [comment]
I think it's a typo. It shouldn't need to extends. Scala just happens to work fine with it and ignores it =P
