### ISSUE TITLE
Origin http://lihaoyi.github.io is not allowed by Access-Control-Allow-Origin when running the weather app.

### ISSUE THREAD

**Issue by Renkai** [lihaoyi/hands-on-scala-js#31]
On my localhost,this error throw,too.
It seems add some config to http response header can fix this error.
But I don't know how to do this with ~fastOptJS.
Have you disabled some browser security settings when test this sample?

**Comment by lihaoyi** [comment]
I suspect this is the same problem as https://github.com/lihaoyi/hands-on-scala-js/issues/30...
